/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as NetworkAnalysisRouteImport } from './routes/network-analysis'
import { Route as LiveEventsRouteImport } from './routes/live-events'
import { Route as FraudNetworkRouteImport } from './routes/fraud-network'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkAnalysisRoute = NetworkAnalysisRouteImport.update({
  id: '/network-analysis',
  path: '/network-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveEventsRoute = LiveEventsRouteImport.update({
  id: '/live-events',
  path: '/live-events',
  getParentRoute: () => rootRouteImport,
} as any)
const FraudNetworkRoute = FraudNetworkRouteImport.update({
  id: '/fraud-network',
  path: '/fraud-network',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/dashboard': typeof DashboardRoute
  '/data-sources': typeof DataSourcesRoute
  '/fraud-network': typeof FraudNetworkRoute
  '/live-events': typeof LiveEventsRoute
  '/network-analysis': typeof NetworkAnalysisRoute
  '/signup': typeof SignupRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/dashboard': typeof DashboardRoute
  '/data-sources': typeof DataSourcesRoute
  '/fraud-network': typeof FraudNetworkRoute
  '/live-events': typeof LiveEventsRoute
  '/network-analysis': typeof NetworkAnalysisRoute
  '/signup': typeof SignupRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/dashboard': typeof DashboardRoute
  '/data-sources': typeof DataSourcesRoute
  '/fraud-network': typeof FraudNetworkRoute
  '/live-events': typeof LiveEventsRoute
  '/network-analysis': typeof NetworkAnalysisRoute
  '/signup': typeof SignupRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases'
    | '/dashboard'
    | '/data-sources'
    | '/fraud-network'
    | '/live-events'
    | '/network-analysis'
    | '/signup'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cases'
    | '/dashboard'
    | '/data-sources'
    | '/fraud-network'
    | '/live-events'
    | '/network-analysis'
    | '/signup'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/cases'
    | '/dashboard'
    | '/data-sources'
    | '/fraud-network'
    | '/live-events'
    | '/network-analysis'
    | '/signup'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRoute: typeof CasesRoute
  DashboardRoute: typeof DashboardRoute
  DataSourcesRoute: typeof DataSourcesRoute
  FraudNetworkRoute: typeof FraudNetworkRoute
  LiveEventsRoute: typeof LiveEventsRoute
  NetworkAnalysisRoute: typeof NetworkAnalysisRoute
  SignupRoute: typeof SignupRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network-analysis': {
      id: '/network-analysis'
      path: '/network-analysis'
      fullPath: '/network-analysis'
      preLoaderRoute: typeof NetworkAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-events': {
      id: '/live-events'
      path: '/live-events'
      fullPath: '/live-events'
      preLoaderRoute: typeof LiveEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fraud-network': {
      id: '/fraud-network'
      path: '/fraud-network'
      fullPath: '/fraud-network'
      preLoaderRoute: typeof FraudNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRoute: CasesRoute,
  DashboardRoute: DashboardRoute,
  DataSourcesRoute: DataSourcesRoute,
  FraudNetworkRoute: FraudNetworkRoute,
  LiveEventsRoute: LiveEventsRoute,
  NetworkAnalysisRoute: NetworkAnalysisRoute,
  SignupRoute: SignupRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
